In [ ]:
https://drive.google.com/drive/folders/1lgXm5Lyqjdkisn1G9c-MqaeLT4boNIzg

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import  drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
columns movie_1 movie_2 movie3 movie4 movie5
row
user_1   2        0      4
user_2   NaN      4      5
user_3   NaN      3      NaN

#user1:
#movie2:3.6, movie4: 4.5, movie5:1.2
#john wick-5 action
#mission impossible

In [ ]:
      13    16      4  75  18
2132
12321
32212

In [ ]:
#svd-singular value decomposition

In [ ]:
R=np.array([[5,3,0,1,0],[4,0,0,1,3],[1,1,0,0,5],[0,0,5,4,1]])
R

array([[5, 3, 0, 1, 0],
       [4, 0, 0, 1, 3],
       [1, 1, 0, 0, 5],
       [0, 0, 5, 4, 1]])

In [ ]:
4500
7000000,4500

In [ ]:
#step2:
R=U∑V(T)
U-> left singular matrix of R,(R*R(T))-eigen vectors
∑-> diagonal matrix-> sqrt of eigen values of (R*R(T))
V(T)-> right singular matrix of R, (R(T)*R)

In [ ]:
[m,0,0]
[0,n,0]
[0,0,p]

In [ ]:
R

array([[5, 3, 0, 1, 0],
       [4, 0, 0, 1, 3],
       [1, 1, 0, 0, 5],
       [0, 0, 5, 4, 1]])

In [ ]:
R.T

array([[5, 4, 1, 0],
       [3, 0, 1, 0],
       [0, 0, 0, 5],
       [1, 1, 0, 4],
       [0, 3, 5, 1]])

In [ ]:
R_RT=np.matmul(R,R.T)#row*column
R_RT

array([[35, 21,  8,  4],
       [21, 26, 19,  7],
       [ 8, 19, 27,  5],
       [ 4,  7,  5, 42]])

In [ ]:
eig_v,eig_vector=np.linalg.eig(R_RT)

In [ ]:
eig_v

array([65.55483301,  3.32549744, 22.50694918, 38.61272037])

In [ ]:
U=eig_vector
U

array([[ 0.56709092,  0.38987276,  0.65517193, -0.31169994],
       [ 0.58310894, -0.78074828, -0.12791167, -0.18453913],
       [ 0.45244514,  0.48680929, -0.73772884, -0.1186013 ],
       [ 0.36562993,  0.03805351,  0.1007199 ,  0.92451186]])

In [ ]:
d_matrix=np.array([[np.sqrt(65.55483301),0,0,0],[0,np.sqrt(3.32549744),0,0],[0,0,np.sqrt(22.50694918),0],[0,0,0,np.sqrt(38.61272037)]])

In [ ]:
d_matrix

array([[8.09659391, 0.        , 0.        , 0.        ],
       [0.        , 1.82359465, 0.        , 0.        ],
       [0.        , 0.        , 4.74414894, 0.        ],
       [0.        , 0.        , 0.        , 6.21391345]])

In [ ]:
R_RT

array([[35, 21,  8,  4],
       [21, 26, 19,  7],
       [ 8, 19, 27,  5],
       [ 4,  7,  5, 42]])

In [ ]:
RT_R=np.matmul(R.T,R)
RT_R

array([[42, 16,  0,  9, 17],
       [16, 10,  0,  3,  5],
       [ 0,  0, 25, 20,  5],
       [ 9,  3, 20, 18,  7],
       [17,  5,  5,  7, 35]])

In [ ]:
eig_v,eig_vector=np.linalg.eig(RT_R)
eig_vector

array([[-0.69416048, -0.38868542, -0.42715441, -0.37662979, -0.20677038],
       [-0.26600296, -0.16957126, -0.25880026,  0.908331  ,  0.09189795],
       [-0.22579243,  0.74390468, -0.10615171,  0.10433653, -0.61112135],
       [-0.32269367,  0.5152644 , -0.19606043, -0.1308742 ,  0.75815806],
       [-0.54062023, -0.03574431,  0.83717003,  0.07120832,  0.02297449]])

In [ ]:
V_T=eig_vector.T
V_T

array([[-0.69416048, -0.26600296, -0.22579243, -0.32269367, -0.54062023],
       [-0.38868542, -0.16957126,  0.74390468,  0.5152644 , -0.03574431],
       [-0.42715441, -0.25880026, -0.10615171, -0.19606043,  0.83717003],
       [-0.37662979,  0.908331  ,  0.10433653, -0.1308742 ,  0.07120832],
       [-0.20677038,  0.09189795, -0.61112135,  0.75815806,  0.02297449]])

In [ ]:

#step3:low rank approximation
d_matrix

array([[8.09659391, 0.        , 0.        , 0.        ],
       [0.        , 1.82359465, 0.        , 0.        ],
       [0.        , 0.        , 4.74414894, 0.        ],
       [0.        , 0.        , 0.        , 6.21391345]])

In [ ]:
d=d_matrix[:2,:2]
d

array([[8.09659391, 0.        ],
       [0.        , 1.82359465]])

In [ ]:
U_2=U[:,:2]
U_2

array([[ 0.56709092,  0.38987276],
       [ 0.58310894, -0.78074828],
       [ 0.45244514,  0.48680929],
       [ 0.36562993,  0.03805351]])

In [ ]:
#matmul- no of columns of mat1 should match with no of rows of matr2
#matmul of U_2, d is (4,2)
#v_t->

array([[37.17555088,  1.29652085],
       [38.22560895, -2.59637641],
       [29.65996564,  1.61888305],
       [23.96880904,  0.12654684]])

In [ ]:
print(V_T)
V_T_2=V_T[:2,:]
V_T_2

[[-0.69416048 -0.26600296 -0.22579243 -0.32269367 -0.54062023]
 [-0.38868542 -0.16957126  0.74390468  0.5152644  -0.03574431]
 [-0.42715441 -0.25880026 -0.10615171 -0.19606043  0.83717003]
 [-0.37662979  0.908331    0.10433653 -0.1308742   0.07120832]
 [-0.20677038  0.09189795 -0.61112135  0.75815806  0.02297449]]


array([[-0.69416048, -0.26600296, -0.22579243, -0.32269367, -0.54062023],
       [-0.38868542, -0.16957126,  0.74390468,  0.5152644 , -0.03574431]])

In [ ]:
U_2

array([[ 0.56709092,  0.38987276],
       [ 0.58310894, -0.78074828],
       [ 0.45244514,  0.48680929],
       [ 0.36562993,  0.03805351]])

In [ ]:
d

array([[8.09659391, 0.        ],
       [0.        , 1.82359465]])

In [ ]:
V_T_2

array([[-0.69416048, -0.26600296, -0.22579243, -0.32269367, -0.54062023],
       [-0.38868542, -0.16957126,  0.74390468,  0.5152644 , -0.03574431]])

In [ ]:
#step4: rating matrix
#R=U∑V(T)

In [ ]:
r=np.matmul(U_2,d)
r_mat=np.abs(np.matmul(r,V_T_2))
r_mat

array([[3.46358488, 1.34191394, 0.50783326, 1.1153121 , 2.50767357],
       [2.72386985, 1.01442196, 2.12515837, 2.2571173 , 2.50148258],
       [2.88794618, 1.12497487, 0.16674139, 0.72469001, 2.01216668],
       [2.08193539, 0.79923099, 0.61680358, 0.91953213, 1.60290936]])

In [ ]:
#1-5

In [ ]:
R

array([[5, 3, 0, 1, 0],
       [4, 0, 0, 1, 3],
       [1, 1, 0, 0, 5],
       [0, 0, 5, 4, 1]])

In [ ]:
#mounted drive
# netflix_data=pd.read_csv(r'/content/drive/MyDrive/combined_data (1).txt',header=None,
#                          names=['Cust_id','Rating'],usecols=[0,1])
# netflix_data

In [ ]:
#manual way
netflix_data=pd.read_csv(r'/content/combinedNetflixData (1).txt',header=None,names=['Cust_id','Rating'],usecols=[0,1])
netflix_data

Cust_id  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [ ]:
netflix_data[netflix_data['Cust_id']=='2:']

Cust_id  Rating
548      2:     NaN

In [ ]:
netflix_data.iloc[0:548]

Cust_id  Rating
0         1:     NaN
1    1488844     3.0
2     822109     5.0
3     885013     4.0
4      30878     4.0
..       ...     ...
543  1790158     4.0
544  1403184     3.0
545  1535440     4.0
546  1426604     4.0
547  1815755     5.0

[548 rows x 2 columns]

In [ ]:
#how many movies are there in the dataset

In [ ]:
movie_count=netflix_data.isnull().sum().iloc[1]
movie_count

4499

In [ ]:
netflix_data[netflix_data['Rating'].isnull()]

Cust_id  Rating
0             1:     NaN
548           2:     NaN
694           3:     NaN
2707          4:     NaN
2850          5:     NaN
...          ...     ...
24046714   4495:     NaN
24047329   4496:     NaN
24056849   4497:     NaN
24057564   4498:     NaN
24057834   4499:     NaN

[4499 rows x 2 columns]

In [ ]:
netflix_data.head()

Cust_id  Rating
0       1:     NaN
1  1488844     3.0
2   822109     5.0
3   885013     4.0
4    30878     4.0

In [ ]:
netflix_data[netflix_data['Cust_id']=='1488844']

Cust_id  Rating
1         1488844     3.0
5157      1488844     4.0
24369     1488844     2.0
93296     1488844     3.0
224788    1488844     3.0
...           ...     ...
23953934  1488844     5.0
23982076  1488844     2.0
23985697  1488844     5.0
24020180  1488844     3.0
24040224  1488844     3.0

[529 rows x 2 columns]

In [ ]:
#customer count after subtracting movie count
netflix_data['Cust_id'].nunique()-movie_count

470758

In [ ]:
# count of each ratings

In [ ]:
netflix_data['Rating'].value_counts()

Rating
4.0    8085741
3.0    6904181
5.0    5506583
2.0    2439073
1.0    1118186
Name: count, dtype: int64

In [ ]:
netflix_data

Cust_id  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [ ]:
current_movie_id=None
movie_ids=[]
for id in netflix_data['Cust_id']:
  if ':' in id:
    current_movie_id=int(id.replace(':',''))
  movie_ids.append(current_movie_id)

netflix_data['movie ID']=movie_ids

In [ ]:
netflix_data

Cust_id  Rating  movie ID
0              1:     NaN         1
1         1488844     3.0         1
2          822109     5.0         1
3          885013     4.0         1
4           30878     4.0         1
...           ...     ...       ...
24058258  2591364     2.0      4499
24058259  1791000     2.0      4499
24058260   512536     5.0      4499
24058261   988963     3.0      4499
24058262  1704416     3.0      4499

[24058263 rows x 3 columns]

In [ ]:
netflix_data.dropna(inplace=True)

In [ ]:
netflix_data=netflix_data.reset_index().drop('index',axis=1)
netflix_data

Cust_id  Rating  movie ID
0         1488844     3.0         1
1          822109     5.0         1
2          885013     4.0         1
3           30878     4.0         1
4          823519     3.0         1
...           ...     ...       ...
24053759  2591364     2.0      4499
24053760  1791000     2.0      4499
24053761   512536     5.0      4499
24053762   988963     3.0      4499
24053763  1704416     3.0      4499

[24053764 rows x 3 columns]

In [ ]:
netflix_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24053764 entries, 0 to 24053763
Data columns (total 3 columns):
 #   Column    Dtype  
---  ------    -----  
 0   Cust_id   object 
 1   Rating    float64
 2   movie ID  int64  
dtypes: float64(1), int64(1), object(1)
memory usage: 550.5+ MB


In [ ]:
#for getting count and average of rating and grouping on movie ids

In [ ]:
f=['count','mean']
ratings_summary=netflix_data.groupby('movie ID')['Rating'].agg(f).reset_index().sort_values(by='count')
ratings_summary

movie ID   count      mean
4361      4362      36  2.000000
4337      4338      39  2.948718
3655      3656      42  3.214286
914        915      43  2.837209
4293      4294      44  4.272727
...        ...     ...       ...
570        571  154832  3.962585
4431      4432  156183  3.755364
3859      3860  160454  3.434517
2151      2152  162597  3.425322
1904      1905  193941  4.153908

[4499 rows x 3 columns]

In [ ]:
benchmark=ratings_summary['count'].quantile(0.7)
benchmark=round(benchmark)
benchmark

1799

In [ ]:
drop_list=ratings_summary[ratings_summary['count']<benchmark].index
drop_list

Index([4361, 4337, 3655,  914, 4293,  819, 2804, 3692, 4034, 1857,
       ...
       2276, 2949, 2523, 3808, 1154, 3997, 2058, 2092, 1104, 1940],
      dtype='int64', length=3149)

In [ ]:
final_df=netflix_data[~netflix_data['movie ID'].isin(drop_list)]
final_df

Cust_id  Rating  movie ID
547       2059652     4.0         2
548       1666394     3.0         2
549       1759415     4.0         2
550       1959936     5.0         2
551        998862     4.0         2
...           ...     ...       ...
24053759  2591364     2.0      4499
24053760  1791000     2.0      4499
24053761   512536     5.0      4499
24053762   988963     3.0      4499
24053763  1704416     3.0      4499

[7017289 rows x 3 columns]

In [ ]:
final_df.columns

Index(['Cust_id', 'Rating', 'movie ID'], dtype='object')

In [ ]:
#1412,4299

In [ ]:
title=pd.read_csv(r'/content/movies (1).csv')

In [ ]:
title

movieId                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
87580   292731           The Monroy Affaire (2022)   
87581   292737          Shelter in Solitude (2023)   
87582   292753                         Orca (2023)   
87583   292755              The Angry Breed (1968)   
87584   292757           Race to the Summit (2023)   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
87580                                        Drama  
87581                                 Comedy|Drama  
87582                                        Drama  
87583                                        Drama  
87584                 Action|Adventure|Documentary  

[87585 rows x 3 columns]

In [ ]:
#
!pip install scikit-surprise

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 3.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp311-cp311-linux_x86_64.whl size=2505218 sha256=7564f0198eec4b3c794976023dbe3a4ade88258128d9617595cf8b40754777d1
  Stored in directory: /root/.cache/pip/wheels/2a/8f/6e/7e2899163e2d85d8266daab4aa1cdabec7a6c56f83c015b5af
Successfully built scikit-surprise


In [ ]:
np.__version__

'2.0.2'

In [ ]:
pip install numpy==1.26.4

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 71.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.4
    Uninstalling numpy-2.2.4:
      Successfully uninstalled numpy-2.2.4


In [ ]:
import math
import seaborn as sns
import numpy as np

from surprise import Reader,Dataset,SVD
from surprise.model_selection import cross_validate

In [ ]:
#loading the reader library
reader=Reader()

In [ ]:
data=Dataset.load_from_df(final_df[['Cust_id', 'Rating', 'movie ID']][:100000],reader)

In [ ]:
svd=SVD()

In [ ]:
data-100%(5 folds)
a b c d e

#80 train 20% test
iter1:
a,b,c,d-train
e-test
#rmse
iter2:
a,b,c,e-train
d-train

In [ ]:
rmse=(∑(actual-pred)^2)/n
mae=(∑|actual-pred|)/n

In [ ]:
cross_validate(svd,data,measures=['RMSE','MAE'],verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    77.8906 77.7478 77.6205 78.1294 77.4819 77.7740 0.2234  
MAE (testset)     67.7302 67.4269 67.4035 67.7322 67.2318 67.5050 0.1967  
Fit time          2.89    1.87    1.87    1.88    1.86    2.07    0.41    
Test time         0.13    0.11    0.12    0.12    0.11    0.12    0.01    


{'test_rmse': array([77.89056329, 77.7477855 , 77.62051114, 78.12936804, 77.48187498]),
 'test_mae': array([67.73025, 67.42685, 67.40355, 67.73225, 67.23185]),
 'fit_time': (2.8920645713806152,
  1.8669984340667725,
  1.8711090087890625,
  1.8802030086517334,
  1.8642287254333496),
 'test_time': (0.12861847877502441,
  0.11274313926696777,
  0.11526012420654297,
  0.11807751655578613,
  0.10899162292480469)}

In [ ]:
10000*

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7017289 entries, 547 to 24053763
Data columns (total 3 columns):
 #   Column    Dtype  
---  ------    -----  
 0   Cust_id   int64  
 1   Rating    float64
 2   movie ID  int64  
dtypes: float64(1), int64(2)
memory usage: 214.2 MB


In [ ]:
final_df['Cust_id']=final_df['Cust_id'].astype('int')

<ipython-input-38-f1e9cffd188c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Cust_id']=final_df['Cust_id'].astype('int')


In [ ]:
#
np.random.choice(final_df['Cust_id'])

1831014

In [ ]:
title.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [ ]:
title=title.rename(columns={'movieId':'movie ID','title':'title','genres':'generes'})
title

movie ID                               title  \
0             1                    Toy Story (1995)   
1             2                      Jumanji (1995)   
2             3             Grumpier Old Men (1995)   
3             4            Waiting to Exhale (1995)   
4             5  Father of the Bride Part II (1995)   
...         ...                                 ...   
87580    292731           The Monroy Affaire (2022)   
87581    292737          Shelter in Solitude (2023)   
87582    292753                         Orca (2023)   
87583    292755              The Angry Breed (1968)   
87584    292757           Race to the Summit (2023)   

                                           generes  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
87580                                        Drama  
87581                                 Comedy|Drama  
87582                                        Drama  
87583                                        Drama  
87584                 Action|Adventure|Documentary  

[87585 rows x 3 columns]

In [ ]:
user_1831014=final_df[(final_df['Cust_id']==1831014)&(final_df['Rating']==5)]
user_1831014=pd.merge(user_1831014,title,on='movie ID')
user_1831014[['movie ID','title']]

movie ID                                              title
0        241                                       Fluke (1995)
1        311                               Relative Fear (1994)
2        405  Highlander III: The Sorcerer (a.k.a. Highlande...
3        473                             In the Army Now (1994)
4        788                        Nutty Professor, The (1996)
5       1865                              Wild Man Blues (1997)
6       1974                             Friday the 13th (1980)
7       2371                                      Fletch (1985)
8       2456                                 Fly II, The (1989)
9       2464                              Trick or Treat (1986)
10      2558                            Forces of Nature (1999)
11      3181                                       Titus (1999)
12      3223                        Zed & Two Noughts, A (1985)
13      3495                           Roadside Prophets (1992)
14      3887  Went to Coney Island on a Mission From God... ...
15      4345                      Anniversary Party, The (2001)
16      4392                                       Alice (1990)

In [ ]:
user_1831014=title

In [ ]:
user_1831014

movie ID                               title  \
0             1                    Toy Story (1995)   
1             2                      Jumanji (1995)   
2             3             Grumpier Old Men (1995)   
3             4            Waiting to Exhale (1995)   
4             5  Father of the Bride Part II (1995)   
...         ...                                 ...   
87580    292731           The Monroy Affaire (2022)   
87581    292737          Shelter in Solitude (2023)   
87582    292753                         Orca (2023)   
87583    292755              The Angry Breed (1968)   
87584    292757           Race to the Summit (2023)   

                                           generes  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
87580                                        Drama  
87581                                 Comedy|Drama  
87582                                        Drama  
87583                                        Drama  
87584                 Action|Adventure|Documentary  

[87585 rows x 3 columns]

In [ ]:
user_1831014=user_1831014[~user_1831014['movie ID'].isin(drop_list)]
user_1831014

movie ID                         title                       generes  \
1             2                Jumanji (1995)    Adventure|Children|Fantasy   
6             7                Sabrina (1995)                Comedy|Romance   
14           15       Cutthroat Island (1995)      Action|Adventure|Romance   
15           16                 Casino (1995)                   Crime|Drama   
16           17  Sense and Sensibility (1995)                 Drama|Romance   
...         ...                           ...                           ...   
87580    292731     The Monroy Affaire (2022)                         Drama   
87581    292737    Shelter in Solitude (2023)                  Comedy|Drama   
87582    292753                   Orca (2023)                         Drama   
87583    292755        The Angry Breed (1968)                         Drama   
87584    292757     Race to the Summit (2023)  Action|Adventure|Documentary   

       estimation score  
1                     5  
6                     5  
14                    5  
15                    5  
16                    5  
...                 ...  
87580                 5  
87581                 5  
87582                 5  
87583                 5  
87584                 5  

[84512 rows x 4 columns]

In [ ]:
#prediction of rating for user
user_1831014['estimation score']=user_1831014['movie ID'].apply(lambda x:svd.predict(1831014,x).est)

In [ ]:
user_1831014.sort_values('estimation score')
user_1831014.head(10)

movie ID                                              title  \
1          2                                     Jumanji (1995)   
6          7                                     Sabrina (1995)   
14        15                            Cutthroat Island (1995)   
15        16                                      Casino (1995)   
16        17                       Sense and Sensibility (1995)   
24        25                           Leaving Las Vegas (1995)   
26        27                                Now and Then (1995)   
28        29  City of Lost Children, The (Cité des enfants p...   
30        31                             Dangerous Minds (1995)   
31        32          Twelve Monkeys (a.k.a. 12 Monkeys) (1995)   

                                   generes  estimation score  
1               Adventure|Children|Fantasy                 5  
6                           Comedy|Romance                 5  
14                Action|Adventure|Romance                 5  
15                             Crime|Drama                 5  
16                           Drama|Romance                 5  
24                           Drama|Romance                 5  
26                          Children|Drama                 5  
28  Adventure|Drama|Fantasy|Mystery|Sci-Fi                 5  
30                                   Drama                 5  
31                 Mystery|Sci-Fi|Thriller                 5